### ISSUE TITLE
Some features not working

### ISSUE THREAD

**Issue by miranos** [WaiSiuKei/nila3#1]
Hi

Thank you for this awesome share !

Can you share the unminified version for custom modifications please ?

Eraser, changing timeline (1day, etc...) not working.

Is there a way to load datas from CSV file ?

Thank you

**Comment by WaiSiuKei** [comment]
Sorry that I cannot release the unminified version , it is my side project but the intellectual property rights belongs to my compony.
All the feature you listed are easy to impletement but there is not an ETA. I have uploaded a public API defination sample , maybe you can wait for it.
